name: GH4W-Atividade-Modulo4

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Executar um script personalizado
      run: |
        echo "Este é um script personalizado."
        echo "Ele será executado a cada hora."